=== hoxuro/XML-XSD/XSD exercises/practica2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listaVentas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="venta" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="importe" type="xs:double"></xs:element>
                            <xs:element name="comprador" type="xs:string"></xs:element>
                            <xs:element name="vendedor" type="xs:string"></xs:element>
                            <xs:element name="codigofactura" type="xs:ID"></xs:element>
                            <xs:element name="fecha" type="xs:date" minOccurs="0"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hoxuro/XML-XSD/XSD exercises/practica2.xml
<?xml version="1.0" encoding="UTF-8"?>

<listaVentas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./practica2.xsd">
  <venta>
      <importe>1500</importe>
      <comprador>Wile E.Coyote</comprador>
      <vendedor>ACME</vendedor>
      <codigofactura>E17</codigofactura>
  </venta>
  <venta>
      <importe>750</importe>
      <comprador>Elmer Fudd</comprador>
      <vendedor>ACME</vendedor>
      <codigofactura>E18</codigofactura>
      <fecha>2015-02-27</fecha>
 </venta>
 </listaVentas>
